parameters:
- name: imageTag
  type: string
- name: containerRepository
  type: string
- name: containerRegistry
  type: string
- name: containerRegistryPassword
  type: string
- name: containerPort
  type: number
  default: 5000
- name: containerEnv
  type: object
  default:
  - name: n0
    value: v0
  - name: n1
    value: v1
  - name: n2
    value: v2
  - name: n3
    value: v3
  - name: n4
    value: v4
  - name: n5
    value: v5
- name: hostname
  type: string
  default: ''
- name: path
  type: string
  default: /
- name: cname
  type: string
  default: ''
- name: environment
  type: string
- name: kubernetesServiceConnection
  type: string
- name: kubernetesNamespace
  type: string
- name: ingress
  type: object
  default:
    enabled: false
- name: service
  type: object
  default:
    enabled: false
- name: helmMetadata
  type: object
  default:
    releaseName: ''
    chartRegistry: ''
    chartName: ''
    chartVersion: ''

stages:
- stage: Deploy
  jobs:
  - deployment: Deploy
    environment: ${{ parameters.environment }}
    variables:
    - name: HELM_EXPERIMENTAL_OCI
      value: 1
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            - task: KubernetesManifest@0
              inputs:
                action: createSecret
                kubernetesServiceConnection: ${{ parameters.kubernetesServiceConnection }}
                namespace: ${{ parameters.kubernetesNamespace }}
                secretType: dockerRegistry
                secretName: regcred
                dockerRegistryEndpoint: ${{ parameters.containerRegistry }}
            - task: HelmInstaller@1
              displayName: Helm installer
            - script: helm registry login ${{ parameters.helmMetadata.chartRegistry }} -u admin -p ${{ parameters.containerRegistryPassword }}
              displayName: Helm login
            - task: HelmDeploy@0
              inputs:
                connectionType: 'Kubernetes Service Connection'
                kubernetesServiceConnection: ${{ parameters.kubernetesServiceConnection }}
                namespace: ${{ parameters.kubernetesNamespace }}
                command: upgrade
                install: true
                chartName: oci://${{ parameters.helmMetadata.chartRegistry }}/${{ parameters.helmMetadata.chartName }}
                chartVersion: ${{ parameters.helmMetadata.chartVersion }}
                releaseName: ${{ parameters.helmMetadata.releaseName }}
                overrideValues: |
                  image.repository=${{ parameters.containerRepository }}
                  image.tag=${{ parameters.imageTag }}
                  containerPort=${{ parameters.containerPort }}
                  env[0].name=${{ parameters.containerEnv[0].name }}
                  env[0].value=${{ parameters.containerEnv[0].value }}
                  env[1].name=${{ parameters.containerEnv[1].name }}
                  env[1].value=${{ parameters.containerEnv[1].value }}
                  env[2].name=${{ parameters.containerEnv[2].name }}
                  env[2].value=${{ parameters.containerEnv[2].value }}
                  env[3].name=${{ parameters.containerEnv[3].name }}
                  env[3].value=${{ parameters.containerEnv[3].value }}
                  env[4].name=${{ parameters.containerEnv[4].name }}
                  env[4].value=${{ parameters.containerEnv[4].value }}
                  ingress.enabled=${{ parameters.ingress.enabled }}
                  ingress.hosts[0].host=${{ parameters.hostname }}
                  ingress.hosts[0].paths[0].pathType=Prefix
                  ingress.hosts[0].paths[0].path=${{ parameters.path }}
                  ingress.tls[0].hosts[0]=${{ parameters.hostname }}
                  ingress.tls[0].secretName=${{ format('{0}-{1}', replace(parameters.hostname, '.', '-'), 'cert') }}
                  ingress.annotations.external-dns\.alpha\.kubernetes\.io\/target=${{ parameters.cname }}
                  ingress.annotations.cert-manager\.io\/cluster-issuer=letsencrypt
                  service=${{ parameters.service }}
                  serviceAccount.create=false
