# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/IdentityManager

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'titancamp/identitymanager'
    command: 'buildAndPush'
    Dockerfile: 'src/IdentityManager/WebApi/Dockerfile'
    buildContext: '.'
    tags: |
      $(Build.BuildId)
      latest