version: '3.4'

services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
        - "1433:1433"
    environment: 
        SA_PASSWORD: "Passw0rd!"
        ACCEPT_EULA: "Y"

  redis-cache:
   container_name: redis-cache
   image: "redis:alpine"
   ports:
    - "6379:6379"
   expose:
    - "6379"
  
  tourmanager.api:
    image: ${DOCKER_REGISTRY-}tourmanagerapi
    build:
      context: .
      dockerfile: src/TourManager/TourManager.Api/Dockerfile
    ports:
        - "5000:80"
        - "5001:443"
    depends_on:
        - sql-server-db

  travely.propertymanager.api:
    image: ${DOCKER_REGISTRY-}travelypropertymanagerapi
    build:
      context: .
      dockerfile: src/PropertyManager/Travely.PropertyManager.API/Dockerfile
    ports:
        - "5100:80"
        - "5101:443"
    depends_on:
        - sql-server-db

  travely.clientmanager.service:
    image: ${DOCKER_REGISTRY-}travelyclientmanagerservice
    build:
      context: .
      dockerfile: src/ClientManager/Travely.ClientManager.Service/Dockerfile
    ports:
        - "5110:80"
        - "5111:443"
    depends_on:
        - sql-server-db

  travely.schedulermanager.api:
    image: ${DOCKER_REGISTRY-}travelyschedulermanagerapi
    build:
      context: .
      dockerfile: src/SchedulerManager/Travely.SchedulerManager.API/Dockerfile
    ports:
        - "5200:80"
        - "5201:443"
    depends_on:
        - sql-server-db
        - redis-cache

