version: '3.4'

services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
        - "1433:1433"
    environment: 
        SA_PASSWORD: "Passw0rd!"
        ACCEPT_EULA: "Y"

  redis-cache:
   container_name: redis-cache
   image: "redis:alpine"
   ports:
    - "6379:6379"

  consul:
    image: consul:latest
    command: consul agent -dev -ui -log-level=warn -client=0.0.0.0
    container_name: consul
    hostname: consul
    ports:
     - "8500"

  travely.gateway:
    image: titancamp/travelygateway
    build:
      context: .
      dockerfile: src/Gateway/Travely.Gateway/Dockerfile
    ports:
        - "8000:80"
        - "8001:443"
    env_file:
       - .env
    volumes:
      - ~/.aspnet/https:/https:ro
  
  tourmanager.api:
    image: titancamp/tourmanagerapi
    build:
      context: .
      dockerfile: src/TourManager/TourManager.Api/Dockerfile
    ports:
        - "8700:80"
        - "8701:443"
    depends_on:
        - sql-server-db
    environment:
       - ServiceDiscoveryConfiguration__serviceName=travely-tourmanager
       - ServiceDiscoveryConfiguration__serviceId=travely-tourmanager-1
       - ServiceDiscoveryConfiguration__serviceAddress=http://tourmanager.api
       - ConsulClientConfiguration__address=http://consul:8500
    env_file:
       - .env
    volumes:
      - ~/.aspnet/https:/https:ro

  travely.servicemanager.service:
    image: titancamp/travelyservicemanagerservice
    build:
      context: .
      dockerfile: src/ServiceManager/Travely.ServiceManager.Service/Dockerfile
    ports:
        - "8100:80"
        - "8101:443"
    depends_on:
        - sql-server-db
    environment:
       - ServiceDiscoveryConfiguration__serviceName=travely-servicemanager-service
       - ServiceDiscoveryConfiguration__serviceId=travely-servicemanager-service-1
       - ServiceDiscoveryConfiguration__serviceAddress=http://travely.servicemanager.service
       - ConsulClientConfiguration__address=http://consul:8500
    env_file:
       - .env
    volumes:
      - ~/.aspnet/https:/https:ro

  travely.schedulermanager.api:
    image: titancamp/travelyschedulermanagerapi
    build:
      context: .
      dockerfile: src/SchedulerManager/Travely.SchedulerManager.API/Dockerfile
    ports:
        - "8200:80"
        - "8201:443"
    depends_on:
        - sql-server-db
    environment:
       - ServiceDiscoveryConfiguration__serviceName=travely-schedulermanager-api
       - ServiceDiscoveryConfiguration__serviceId=travely-schedulermanager-api-1
       - ServiceDiscoveryConfiguration__serviceAddress=http://travely.schedulermanager.api
       - ConsulClientConfiguration__address=http://consul:8500
    env_file:
       - .env
    volumes:
      - ~/.aspnet/https:/https:ro

  travely.propertymanager.api:
    image: titancamp/travelypropertymanagerapi
    build:
      context: .
      dockerfile: src/PropertyManager/Travely.PropertyManager.API/Dockerfile
    ports:
        - "8300:80"
        - "8301:443"
    depends_on:
        - sql-server-db
    environment:
       - ServiceDiscoveryConfiguration__serviceName=travely-propertymanager-api
       - ServiceDiscoveryConfiguration__serviceId=travely-propertymanager-api-1
       - ServiceDiscoveryConfiguration__serviceAddress=http://travely.propertymanager.api
       - ConsulClientConfiguration__address=http://consul:8500
    env_file:
       - .env
    volumes:
      - ~/.aspnet/https:/https:ro


  fileservice:
    image: titancamp/fileservice
    build:
      context: .
      dockerfile: src/FileServiceManager/FileService/Dockerfile
    ports:
        - "8400:80"
        - "8401:443"
    depends_on:
        - sql-server-db
    environment:
       - ServiceDiscoveryConfiguration__serviceName=fileservice
       - ServiceDiscoveryConfiguration__serviceId=fileservice-1
       - ServiceDiscoveryConfiguration__serviceAddress=http://fileservice
       - ConsulClientConfiguration__address=http://consul:8500
    env_file:
       - .env
    volumes:
      - ~/.aspnet/https:/https:ro


  travely.clientmanager.service:
    image: titancamp/travelyclientmanagerservice
    hostname: travely.clientmanager.service
    build:
      context: .
      dockerfile: src/ClientManager/Travely.ClientManager.Service/Dockerfile
    ports:
        - "8500:80"
        - "8501:443"
    depends_on:
        - sql-server-db
    environment:
       - ServiceDiscoveryConfiguration__serviceName=travely-clientmanager-service
       - ServiceDiscoveryConfiguration__serviceId=travely-clientmanager-service-1
       - ServiceDiscoveryConfiguration__serviceAddress=http://travely.clientmanager.service
       - ConsulClientConfiguration__address=http://consul:8500
    env_file:
       - .env
    volumes:
      - ~/.aspnet/https:/https:ro


  travely.identity.webapi:
    image: titancamp/travelyidentitywebapi
    build:
      context: .
      dockerfile: src/IdentityManager/WebApi/Dockerfile
    ports:
      - "8600:80"
      - "8601:443"
    depends_on:
      - sql-server-db
    environment:
       - ServiceDiscoveryConfiguration__serviceName=travely-identity-webapi
       - ServiceDiscoveryConfiguration__serviceId=travely-identity-webapi-1
       - ServiceDiscoveryConfiguration__serviceAddress=http://travely.identity.webapi
       - ConsulClientConfiguration__address=http://consul:8500
    env_file:
       - .env
    volumes:
      - ~/.aspnet/https:/https:ro

     
  travely.reportingmanager:
    image: titancamp/travelyreportingmanager
    build:
      context: .
      dockerfile: src/ReportingManager/Travely.ReportingManager/Dockerfile
    ports:
        - "8800:80"
        - "8801:443"
    depends_on:
        - sql-server-db
    environment:
       - ServiceDiscoveryConfiguration__serviceName=travely-reportingmanager
       - ServiceDiscoveryConfiguration__serviceId=travely-reportingmanager-1
       - ServiceDiscoveryConfiguration__serviceAddress=http://travely.reportingmanager
       - ConsulClientConfiguration__address=http://consul:8500
    env_file:
      - .env
    volumes:
      - ~/.aspnet/https:/https:ro
