version: '3.4'

services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
        - "1433:1433"
    environment: 
        SA_PASSWORD: "Passw0rd!"
        ACCEPT_EULA: "Y"

  redis-cache:
   container_name: redis-cache
   image: "redis:alpine"
   ports:
    - "6379:6379"
  
  tourmanager.api:
    image: titancamp/tourmanagerapi
    build:
      context: .
      dockerfile: src/TourManager/TourManager.Api/Dockerfile
    ports:
        - "8000:80"
        - "8001:443"
    depends_on:
        - sql-server-db
    environment:
        - ASPNETCORE_URLS=https://+:443;http://+:80
        - ASPNETCORE_Kestrel__Certificates__Default__Password=admin
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro

  travely.servicemanager.service:
    image: titancamp/travelyservicemanagerservice
    build:
      context: .
      dockerfile: src/ServiceManager/Travely.ServiceManager.Service/Dockerfile
    ports:
        - "8100:80"
        - "8101:443"
    depends_on:
        - sql-server-db
    environment:
        - ASPNETCORE_URLS=https://+:443;http://+:80
        - ASPNETCORE_Kestrel__Certificates__Default__Password=admin
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro

  travely.schedulermanager.api:
    image: titancamp/travelyschedulermanagerapi
    build:
      context: .
      dockerfile: src/SchedulerManager/Travely.SchedulerManager.API/Dockerfile
    ports:
        - "8200:80"
        - "8201:443"
    depends_on:
        - sql-server-db
    environment:
        - ASPNETCORE_URLS=https://+:443;http://+:80
        - ASPNETCORE_Kestrel__Certificates__Default__Password=admin
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro

  travely.propertymanager.api:
    image: titancamp/travelypropertymanagerapi
    build:
      context: .
      dockerfile: src/PropertyManager/Travely.PropertyManager.API/Dockerfile
    ports:
        - "8300:80"
        - "8301:443"
    depends_on:
        - sql-server-db
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=admin
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro


  fileservice:
    image: titancamp/fileservice
    build:
      context: .
      dockerfile: src/FileServiceManager/FileService/Dockerfile
    ports:
        - "8400:80"
        - "8401:443"
    depends_on:
        - sql-server-db
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=admin
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro


  travely.clientmanager.service:
    image: titancamp/travelyclientmanagerservice
    build:
      context: .
      dockerfile: src/ClientManager/Travely.ClientManager.Service/Dockerfile
    ports:
        - "8500:80"
        - "8501:443"
    depends_on:
        - sql-server-db
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=admin
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro


  travely.identity.webapi:
    image: titancamp/travelyidentitywebapi
    build:
      context: .
      dockerfile: src/IdentityManager/WebApi/Dockerfile
    ports:
      - "8600:80"
      - "8601:443"
    depends_on:
      - sql-server-db
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=admin
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro

