---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedulermanager-api
  labels:
    app: schedulermanager-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: schedulermanager-api
  template:
    metadata:
      labels:
        app: schedulermanager-api
    spec:
      containers:
      - name: schedulermanager-api
        image: titancamp/schedulermanager:latest
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: schedulermanager-api-service
  namespace: dev
  labels:
    app: schedulermanager-api
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: schedulermanager-api
  type: NodePort
