---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedulermanager-api
  labels:
    app: schedulermanager-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: schedulermanager-api
  template:
    metadata:
      labels:
        app: schedulermanager-api
    spec:
      containers:
      - name: schedulermanager-api
        image: titancamp/schedulermanager:latest
        ports:
        - containerPort: 80
        env:
        - name: "mssql_hostname"
          valueFrom:
            secretKeyRef:
              name: dbconnection
              key: hostname
        - name: "mssql_password"
          valueFrom:
            secretKeyRef:
              name: dbconnection
              key: password
        - name: "mssql_username"
          valueFrom:
            secretKeyRef:
              name: dbconnection
              key: username
        - name: "mssql_port"
          valueFrom:
            secretKeyRef:
              name: dbconnection
              key: port  
---
kind: Service
apiVersion: v1
metadata:
  name: schedulermanager-api-service
  namespace: dev
  labels:
    app: schedulermanager-api
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    app: schedulermanager-api
  type: NodePort
