// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Travely.TourManager.DAL;

namespace Travely.TourManager.DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220209184346_Tour-V4")]
    partial class TourV4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Travely.TourManager.DAL.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ArrivalDate");

                    b.Property<string>("ArrivalFlightNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ArrivalFlightNumber");

                    b.Property<string>("ArrivalLocation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ArrivalLocation");

                    b.Property<TimeSpan>("ArrivalTime")
                        .HasColumnType("time")
                        .HasColumnName("ArrivalTime");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DepartureDate");

                    b.Property<string>("DepartureFlightNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DepartureFlightNumber");

                    b.Property<string>("DepartureLocation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DepartureLocation");

                    b.Property<TimeSpan>("DepartureTime")
                        .HasColumnType("time")
                        .HasColumnName("DepartureTime");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EndDate");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Notes");

                    b.Property<string>("PartnerName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PartnerName");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartDate");

                    b.Property<string>("TourName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TourName");

                    b.Property<int>("TourStatusId")
                        .HasColumnType("int")
                        .HasColumnName("TourStatusId");

                    b.Property<int>("TourTypeId")
                        .HasColumnType("int")
                        .HasColumnName("TourTypeId");

                    b.HasKey("Id");

                    b.HasIndex("TourStatusId");

                    b.HasIndex("TourTypeId");

                    b.ToTable("Tour");
                });

            modelBuilder.Entity("Travely.TourManager.DAL.TourStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StatusName");

                    b.HasKey("Id");

                    b.ToTable("TourStatus");
                });

            modelBuilder.Entity("Travely.TourManager.DAL.TourType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TypeName");

                    b.HasKey("Id");

                    b.ToTable("TourType");
                });

            modelBuilder.Entity("Travely.TourManager.DAL.Tour", b =>
                {
                    b.HasOne("Travely.TourManager.DAL.TourStatus", "TourStatus")
                        .WithMany("Tours")
                        .HasForeignKey("TourStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Travely.TourManager.DAL.TourType", "TourType")
                        .WithMany("Tours")
                        .HasForeignKey("TourTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TourStatus");

                    b.Navigation("TourType");
                });

            modelBuilder.Entity("Travely.TourManager.DAL.TourStatus", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("Travely.TourManager.DAL.TourType", b =>
                {
                    b.Navigation("Tours");
                });
#pragma warning restore 612, 618
        }
    }
}
