---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicemanager-service
  labels:
    app: servicemanager-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicemanager-service
  template:
    metadata:
      labels:
        app: servicemanager-service
    spec:
      containers:
      - name: servicemanager-service
        image: titancamp/servicemanager:latest
        ports:
        - containerPort: 80
        env:
        - name: "mssql_hostname"
          valueFrom:
            secretKeyRef:
              name: dbconnection
              key: hostname
        - name: "mssql_password"
          valueFrom:
            secretKeyRef:
              name: dbconnection
              key: password
        - name: "mssql_username"
          valueFrom:
            secretKeyRef:
              name: dbconnection
              key: username
        - name: "mssql_port"
          valueFrom:
            secretKeyRef:
              name: dbconnection
              key: port
---
kind: Service
apiVersion: v1
metadata:
  name: servicemanager-service-service
  namespace: dev
  labels:
    app: servicemanager-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    app: servicemanager-service
  type: NodePort
