trigger:
  branches:
    include:
    - develop
  paths:
    include:
    - src/TourManager
pr:
  branches:
    include:
    - develop
  paths:
    include:
    - src/TourManager

variables:
- group: travely-dev
- name: project
  value: tour-manager
- name: gitBranch
  value: $(Build.SourceBranchName)
- name: imageTag
  value: $(Build.BuildId)
- name: containerRepository
  value: travely/$(project)/$(gitBranch)
- name: containerRegistry
  value: registry-travely-am
- name: containerRegistryHost
  value: registry.travely.am

stages:
# Build stage
- template: templates/build.yml
  parameters:
    imageTag: $(imageTag)
    containerRepository: $(containerRepository)
    containerRegistry: $(containerRegistry)
    dockerFile: src/TourManager/TourManager.Api/Dockerfile
# Deploy stage
- template: templates/deploy.yml
  parameters:
    imageTag: $(imageTag)
    containerRepository: $(containerRegistryHost)/$(containerRepository)
    containerRegistry: $(containerRegistry)
    containerRegistryPassword: $(registry_travely_am_password)
    containerPort: 80
    containerEnv:
    - name: ConnectionStrings__TourDbContext
      value: Server=mssql;Database=Tour;User=sa;Password=$(mssql_sa_password)
    - name: TravelyIdentityConfig__Authority
      value: http://tour-manager-app
    - name: n2
      value: v2
    - name: n3
      value: v3
    - name: n4
      value: v4
    environment: dev.dev-travely-am
    kubernetesServiceConnection: dev-dev-travely-am-1639235401610
    kubernetesNamespace: dev-travely-am
    helmMetadata:
      releaseName: $(project)
      chartRegistry: $(containerRegistryHost)
      chartName: helm-charts/app
      chartVersion: 0.1.2
