trigger:
  - devops

variables:
- group: travely
- name: project
  value: client-manager
- name: imageTag
  value: $(Build.BuildId)
- name: containerRepository
  value: travely/$(project)
- name: containerRegistry
  value: registry-travely-am
- name: containerRegistryHost
  value: registry.travely.am
- name: gitBranch
  value: $(Build.SourceBranchName)

stages:
- stage:
  jobs:
    - job: echo
      steps:
        - script: echo $(my-test-var)
# Build stage
- template: templates/build.yml
  parameters:
    imageTag: $(imageTag)
    containerRepository: $(containerRepository)
    containerRegistry: $(containerRegistry)
    dockerFile: src/ClientManager/Travely.ClientManager.Service/Dockerfile
# Deploy stage
- template: templates/deploy.yml
  parameters:
    imageTag: $(imageTag)
    containerRepository: $(containerRegistryHost)/$(containerRepository)
    containerRegistry: $(containerRegistry)
    containerRegistryPassword: $(registry_travely_am_password)
    containerPort: 5000
    hostname: $(project).travely.am
    path: /
    cname: k8s.travely.am
    environment: dev.dev-travely-am
    kubernetesServiceConnection: dev-dev-travely-am-1639235401610
    kubernetesNamespace: dev-travely-am
    ingress:
      enabled: true
    helmMetadata:
      releaseName: $(project)
      chartRegistry: $(containerRegistryHost)
      chartName: helm-charts/app
      chartVersion: 0.1.1
