trigger:
  branches:
    include:
    - develop
  paths:
    include:
    - src/Gateway

variables:
- group: travely
- name: project
  value: gateway
- name: imageTag
  value: $(Build.BuildId)
- name: containerRepository
  value: travely/$(project)
- name: containerRegistry
  value: registry-travely-am
- name: containerRegistryHost
  value: registry.travely.am
- name: gitBranch
  value: $(Build.SourceBranchName)

stages:
# Build stage
- template: templates/build.yml
  parameters:
    imageTag: $(imageTag)
    containerRepository: $(containerRepository)
    containerRegistry: $(containerRegistry)
    dockerFile: src/Gateway/Travely.Gateway/Dockerfile
# Deploy stage
- template: templates/deploy.yml
  parameters:
    imageTag: $(imageTag)
    containerRepository: $(containerRegistryHost)/$(containerRepository)
    containerRegistry: $(containerRegistry)
    containerRegistryPassword: $(registry_travely_am_password)
    containerPort: 80
    containerEnv:
    - name: TravelyIdentityConfig__Authority
      value: http://identity-manager-app
    - name: ASPNETCORE_ENVIRONMENT
      value: $(Build.SourceBranchName)
    - name: n2
      value: v2
    - name: n3
      value: v3
    - name: n4
      value: v4
    hostname: $(project).travely.am
    path: /
    cname: k8s.travely.am
    environment: dev.dev-travely-am
    kubernetesServiceConnection: dev-dev-travely-am-1639235401610
    kubernetesNamespace: dev-travely-am
    ingress:
      enabled: true
    helmMetadata:
      releaseName: $(project)
      chartRegistry: $(containerRegistryHost)
      chartName: helm-charts/app
      chartVersion: 0.1.2
