trigger:
  branches:
    include:
    - develop
  paths:
    include:
    - src/SchedulerManager
pr:
  branches:
    include:
    - develop
  paths:
    include:
    - src/SchedulerManager

variables:
- group: travely-dev
- name: project
  value: scheduler-manager
- name: gitBranch
  value: $(Build.SourceBranchName)
- name: imageTag
  value: $(Build.BuildId)
- name: containerRepository
  value: travely/$(project)/$(gitBranch)
- name: containerRegistry
  value: registry-travely-am
- name: containerRegistryHost
  value: registry.travely.am

stages:
# Build stage
- template: templates/build.yml
  parameters:
    imageTag: $(imageTag)
    containerRepository: $(containerRepository)
    containerRegistry: $(containerRegistry)
    dockerFile: src/SchedulerManager/Travely.SchedulerManager.API/Dockerfile
# Deploy stage
- ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
  - template: templates/deploy.yml
    parameters:
      imageTag: $(imageTag)
      containerRepository: $(containerRegistryHost)/$(containerRepository)
      containerRegistry: $(containerRegistry)
      containerRegistryPassword: $(registry_travely_am_password)
      containerPort: 80
      containerEnv:
      - name: SeriLog__ConnectionString
        value: Server=mssql;Database=SchedulerDb;User=sa;Password=$(mssql_sa_password)
      - name: RepositoryOptions__ConnectionString
        value: Server=mssql;Database=SchedulerDb;User=sa;Password=$(mssql_sa_password)
      - name: JobOptions__ConnectionString
        value: Server=mssql;Database=SchedulerDb;User=sa;Password=$(mssql_sa_password)
      - name: NotifierOptions__RedisConnectionString
        value: $(redis_password)@redis-headless:6379
      - name: n4
        value: v4
      environment: dev.dev-travely-am
      kubernetesServiceConnection: dev-dev-travely-am-1639235401610
      kubernetesNamespace: dev-travely-am
      helmMetadata:
        releaseName: $(project)
        chartRegistry: $(containerRegistryHost)
        chartName: helm-charts/app
        chartVersion: 0.1.2
