trigger:
  - devops

variables:
  group: travely
  project: client-manager
  imageTag: $(Build.BuildId)
  containerRepository: travely/$(project)
  containerRegistry: registry-travely-am
  containerRegistryHost: registry.travely.am
  gitBranch: $(Build.SourceBranchName)

stages:
# Build stage
- template: templates/build.yml
  parameters:
    imageTag: $(imageTag)
    containerRepository: $(containerRepository)
    containerRegistry: $(containerRegistry)
    dockerFile: src/ClientManager/Travely.ClientManager.Service/Dockerfile
# Deploy stage
- template: templates/deploy.yml
  parameters:
    imageTag: $(imageTag)
    containerRepository: $(containerRegistryHost)/$(containerRepository)
    containerRegistry: $(containerRegistry)
    containerRegistryPassword: $(registry_travely_am_password)
    containerPort: 5000
    hostname: $(project).travely.am
    path: /
    cname: k8s.travely.am
    environment: dev.dev-travely-am
    kubernetesServiceConnection: dev-dev-travely-am-1639235401610
    kubernetesNamespace: dev-travely-am
    ingress:
      enabled: true
    helmMetadata:
      releaseName: $(project)
      chartRegistry: $(containerRegistryHost)
      chartName: helm-charts/app
      chartVersion: 0.1.1
