version: '3.1'

services:

  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: tourdb
    ports:
      - "5434:3306"